### ISSUE TITLE
TypeError: datetime.datetime(2016, 7, 13, 1, 59, 22) is not JSON serializable

### ISSUE THREAD

**Issue by itsahsiao** [ashleyhsia0/tweegle#3]
I am trying to use AngularJS, so I need to make JSON to use the data from tweepy, but I got the following traceback error for the datetime object:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 7, 13, 1, 59, 22) is not JSON serializable
```

**Comment by itsahsiao** [comment]
Found solution here in making the datetime object a serialized version: http://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable-in-python
